name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm build

      - name: Checkout builds branch
        uses: actions/checkout@v4
        with:
          ref: builds
          path: builds-branch

      - name: Copy dist to builds branch
        run: |
          rm -rf builds-branch/*
          cp -r dist/* builds-branch/

      - name: Commit and push
        run: |
          cd builds-branch
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update build from $GITHUB_SHA" || echo "No changes to commit"
          git push origin builds
